
- name: dbserver setup
  hosts: dbsrvgrp
  become: yes
  tasks:
        - name: install maridb on centos
          yum: 
              name: mariadb-server
              state: present
        - name: start and enable mariadb
          service: 
                  name: mariadb
                  state: started
                  enabled: yes
        - name: Create a new database with name 'accounts'
          mysql_db:
                  name: accounts
                  state: present