- name: webserver setup
  hosts: websrvgrp
  become: yes
  tasks:
      - name: install httpd
        yum:
            name: httpd
            state: present
      - name: enable and start httpd
        service:
                name: httpd
                state: started
                enabled: yes
      - name: Copy file with owner and permissions
        copy:
            src: index.html
            dest: /var/www/html/index.html
            owner: root
            group: root
            mode: '0644'
            backup: yes 
- name: dbserver setup
  hosts: dbsrvgrp
  become: yes
  tasks:
        - name: install maridb on centos
          yum: 
              name: mariadb-server
              state: present
        - name: start and enable mariadb
          service: 
                  name: mariadb
                  state: started
                  enabled: yes