
- name: dbserver setup
  hosts: dbsrvgrp
  become: yes
  vars:
      dbname: var_storage
      dbuser: krunal  
      dbpass: 1234
  tasks:
        - debug:
              var: dbname
        - debug: 
              msg: "this is the value of dbuser {{dbuser}}"
        - name: install maridb on centos
          yum: 
              name: mariadb-server
              state: present

        - name: install MySQL-python 
          yum: 
              name: MySQL-python
              state: present

        - name: start and enable mariadb
          service: 
                  name: mariadb
                  state: started
                  enabled: yes

        - name: Create a new database with name 'accounts'
          mysql_db:
                  name: "{{dbname}}"
                  state: present

        - name: Create database user with name 'admin'
          mysql_user:
                    name: "{{dbuser}}"
                    password: "{{dbpass}}"
                    priv: '*.*:ALL'
                    state: present          